### ISSUE TITLE
可以支持下language-babel么，现在bebel默认也支持jsx的

### ISSUE THREAD

**Issue by ccqgithub** [TOP-Chao/atom-react-native-autocomplete#10]
现在 language-javascript-jsx 好久都不更新了，各种es6语法高亮都有问题。可以支持下language-babel么，现在bebel默认也支持jsx的

**Comment by TOP-Chao** [comment]
这个插件我好久都没更新了 api也不正确了~ 我现在没在用react-native 所以没去管它
