### ISSUE TITLE
Is `language-javascript-jsx` really required for this package?

### ISSUE THREAD

**Issue by dodekeract** [TOP-Chao/atom-react-native-autocomplete#12]
I'm having trouble with `language-javascript-jsx`, because it conflicts with the superior `language-babel` package. Removing it fixes all my issues, but unfortunately `atom-react-native-autocomplete` re-installs it without my permission.

---

**Original issue**: gandm/language-babel#341

**Comment by TOP-Chao** [comment]
I'm sorry, the project has stopped maintenance.
