### ISSUE TITLE
Doesn't show auto-completions for react-native

### ISSUE THREAD

**Issue by satya164** [TOP-Chao/atom-react-native-autocomplete#2]
If you import `react-native` as another variable rather than `React`, it doesn't show autocomplete for it. Moreover, it shows autocomplete for whatever you imported as React.

Lately, I've been following this pattern,

```js
import React, { Component, PropTypes } from 'react';
import ReactNative from 'react-native';
```

And I get autocompletions under `React` rather than `ReactNative`

**Comment by TOP-Chao** [comment]
Hi, autocomplete function is to parse the string to complete, the current rules are `React.` prefixed, if you need to do, I'll release a new version, let you setting prefix.

**Comment by satya164** [comment]
@TOP-Chao That'll be very useful. Thanks a lot :)

**Comment by TOP-Chao** [comment]
The new version has been released.
