### ISSUE TITLE
Language Babel 插件下无法正常提示

### ISSUE THREAD

**Issue by lejun** [TOP-Chao/atom-react-native-autocomplete#4]
安装插件[Language Babel](https://atom.io/packages/language-babel),并切换到此**风格**（即`atom`右下角显示 `Bebal ES6 JavaScript`）

输入 `<` 可以提示 `component`（例如 Text/TextInput...）但是`空格`后无法提示这个部件下的其它属性。。。

切换回 `JavaScript(JSX)` 语言风格，则又正常。

**Comment by TOP-Chao** [comment]
因为这种插件是根据代码的输入的scopes来做设定的，该插件依赖插件`language-javascript-jsx`，所以你需要切换到jsx风格，不然不能识别到。

**Comment by lejun** [comment]
THS!!!
