### ISSUE TITLE
DatePickerIOS's minuteInterval enum must be number

### ISSUE THREAD

**Issue by dev-xdyang** [TOP-Chao/atom-react-native-autocomplete#5]
I use the plugin's autocomplete to set minuteInterval to 15 like below:
![2016-05-23 9 12 18](https://cloud.githubusercontent.com/assets/7471748/15472004/8a08c06e-212b-11e6-94a1-4a49b2cdab3e.png)

but got a error:
![simulator screen shot 2016 5 23 9 12 46](https://cloud.githubusercontent.com/assets/7471748/15472154/4c8f7506-212c-11e6-985d-22c18defd555.png)

So I change the minuteInterval to the format like this:
![2016-05-23 9 12 58](https://cloud.githubusercontent.com/assets/7471748/15472040/ab0805a4-212b-11e6-9704-72fac6b515db.png)

It work fine! 

My project package.json is:
{
  "name": "ComponentDemo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "^15.0.2",
    "react-native": "^0.26.1"
  }
}

**Comment by TOP-Chao** [comment]
大侠 我服了你了~ 明明是中国人 作者也是中国人~ 还要强行说英文。
你学习东西不看文档么? 
`minuteInterval ` 是枚举 值应该为 `minuteInterval ={15}` 
插件提示你都是使用`{}` 你硬要强行使用`""` 我没有办法了 ~

**Comment by dev-xdyang** [comment]
对不起，大侠，这个地方插件提示的是使用字符串，所以我才提了这个bug
![2016-05-23 9 33 07](https://cloud.githubusercontent.com/assets/7471748/15472502/1287ef94-212e-11e6-8cd5-ac5bf2183e77.png)

**Comment by TOP-Chao** [comment]
好吧 我的锅 ~ 等下就修复更新
