### ISSUE TITLE
console.log() autocomplete repeat "console"

### ISSUE THREAD

**Issue by ttpro1995** [TOP-Chao/atom-react-native-autocomplete#6]
How to reproduce:
Type the following key
step1: "c"  "o"  "n"  "s"  "enter"  => console  => OK, work as expected
step2: "dot"   "l"   "enter" => console.console.log(); => expected console.log();

**Comment by TOP-Chao** [comment]
I didn't understand the problem you describe

**Comment by ttpro1995** [comment]
When you are trying to type console.log(); the autocomplete result in console.console.log()

Some screenshot:
At first, it look like this
![First image](http://image.prntscr.com/image/ba6ed16c12044052a7daf155f0cb780f.png)
Then when I press enter
![Second](http://image.prntscr.com/image/a69955766bf6406e9fbbbc203d16ab7a.png)

It is expected to have console.log(); with one "console" only
What I expected:
![expected](http://image.prntscr.com/image/83ac5ffdc18244e4be3262220b8a0052.png)

**Comment by TOP-Chao** [comment]
`log` from [autocomplete-snippets](https://atom.io/packages/autocomplete-snippets)
