### ISSUE TITLE
大侠，我安装以后并没有出现牛B闪闪的提示功能

### ISSUE THREAD

**Issue by jun-lu** [TOP-Chao/atom-react-native-autocomplete#7]
atom  1.7.4

**Comment by TOP-Chao** [comment]
`React.`这个是否给予你提示，如果没有应该是安装失败，尝试重新安装。
如果上述给予了提示，但组件没有提示，你确认文件类型是否为**JavaScript with JSX** (ide右下角)
如果不是请更改为该类型，因为插件依赖[language-javascript-jsx](https://atom.io/packages/language-javascript-jsx)，提供了代码作用域，插件是根据作用域来进行提示。

**Comment by hackerys** [comment]
非常好用，谢谢楼主分享

**Comment by huchenme** [comment]
能不能不要 prefix？现在import都是这种format了 
```
import {
  Text
} from 'react-native';
```
